### PR TITLE
add readPatients

### PR DESCRIPTION
**Pull request by ginberg**
hi @cebarboza, maybe it's good to keep the "readPatients" method? Since it is used in the vignette and we can determine based on the file extension which underlying method to call

### CODE REVIEW

**Comment by cebarboza** [comment]
Hi Ger,

I think the approach of dividing with readPatients.xl or readPatients.csv is more explicit to the user, leading to less confusion. 

I explored the option of the file extension, but I think that is more annoying to us to program things like that, as simple as it may seem, than having two separate functions.

readPatients.csv and readPatients.xl may grow in the future quite a lot, so I guess it is better to divide that from now.

**Comment by cebarboza** [comment]
Also I think I'll need to update the vignette, and have examples for the two functions, which I think will have very different purpose by its own. 

readPatients.xl is the approach we have  been working on so far, filling manually an xls file. 

readPatients.csv is an approach useful if we want to subset something more elaborated such as the MIMICIV database.

**Review by cebarboza — COMMENTED** [review]
Great!

**Comment by ginberg** [comment]
great you have made 2 functions to separate the csv and xlsx loading of data, since they have a different purpose. I think it's also nice to be backwards compatible with the readPatients function, so thanks for the merge!

**Pull request merged**
